version: 0.2

phases:
    install:
        commands:
            - pip install -r requirements.txt
    build:
        commands:
            - nikola build
    post_build:
        commands:
            - aws s3 sync output s3://hedgenet.info
